name: Build Libraries and CLI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build dir cache
      id: make-builddir-cache
      uses: actions/cache@v2
      env:
        cache-name: builddir
      with:
        path: ${{ github.workspace }}/build
        key: ${{ matrix.os }}-build-${{ env.cache-name }}

    - name: Create Build Directory
      if: steps.make-builddir-cache.outputs.cache-hit != 'true'
      run: cmake -E make_directory ${{ github.workspace }}/build

    - name: Configure CMake (Single-config)
      if: ${{ runner.os == 'Linux' }}
      working-directory: ${{ github.workspace }}/build
      run: cmake -DCMAKE_BUILD_TYPE="Release" ..

    - name: Configure CMake (Multi-config)
      if: ${{ runner.os == 'Windows' }}
      working-directory: ${{ github.workspace }}/build
      run: cmake -DCMAKE_CONFIGURATION_TYPES="Release" ..

    - name: Build (Single-config)
      if: ${{ runner.os == 'Linux' }}
      working-directory: ${{ github.workspace }}/build
      run: cmake --build .

    - name: Build (Multi-config)
      if: ${{ runner.os == 'Windows' }}
      working-directory: ${{ github.workspace }}/build
      run: cmake --build . --config Release
