name: Build Libraries and CLI

on: [push, pull_request]
env:
  CONFIGURATION: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: OpenCV Cache
      uses: actions/cache@v2
      env:
        cache-name: OpenCV-0
      with:
        path: ${{ github.workspace }}/build/OpenCV-prefix
        key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ hashFiles('opencv/modules/core/include/opencv2/core/version.hpp') }}

    - name: Artifact Cache
      uses: actions/cache@v2
      env:
        cache-name: artifacts
      with:
        path: ${{ github.workspace }}/build/install
        key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ hashFiles('.gitmodules') }}

    - name: Create Build Directory
      run: cmake -E make_directory ${{ github.workspace }}/build

    - name: Configure CMake
      working-directory: ${{ github.workspace }}/build
      run: cmake -DCMAKE_BUILD_TYPE="${CONFIGURATION}" -DCMAKE_CONFIGURATION_TYPES="${CONFIGURATION}" ${GITHUB_WORKSPACE}

    - name: Build
      working-directory: ${{ github.workspace }}/build
      run: cmake --build .
